stages:

- stage:
  displayName: 'Destroi ambiente'
  
  jobs:

  - job: job1
    displayName: 'Destroi infra AWS'

    steps:
      - script: echo "Terraform Init"
        displayName: "Terra Init"


      - script: echo "Terraform Init"
        displayName: "Terra Init"    

      - task: TerraformTaskV2@2
        inputs:
          provider: 'aws'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/provisiona-infra'
          backendServiceAWS: 'aws-hiago'
          backendAWSBucketName: 'backend-tf-hiago'
          backendAWSKey: 'azure/terraform.tfstate'
    

      - script: echo "Terraform destroy"
        displayName: "Terra destroy"    
      - task: TerraformTaskV2@2
        inputs:
          provider: 'aws'
          command: 'destroy'
          workingDirectory: '$(System.DefaultWorkingDirectory)/provisiona-infra'
          environmentServiceNameAWS: 'aws-hiago'
